import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/self/navBar";

const inter = Inter({ subsets: ["latin"] });
const clashGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/ClashGrotesk/ClashGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts//ClashGrotesk/ClashGrotesk-Extralight.otf",
      weight: "200",
    },
    {
      path: "../public/fonts//ClashGrotesk/ClashGrotesk-Light.otf",
      weight: "300",
    },
    {
      path: "../public/fonts//ClashGrotesk/ClashGrotesk-Medium.otf",
      weight: "500",
    },
    {
      path: "../public/fonts//ClashGrotesk/ClashGrotesk-Semibold.otf",
      weight: "600",
    },
    {
      path: "../public/fonts/ClashGrotesk/ClashGrotesk-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-clashGrotesk",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` light ${inter.className} ${clashGrotesk.className}  bg-bgMain relative`}
      >
        {" "}
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
